import { ConfigService } from '@nestjs/config';
import * as cheerio from 'cheerio';
import { ContextService } from '../../context/context.service';
import { Step } from '../proxy-page.step';

/**
 * ### Proxy page step to replace drawio macro by the image generated by Confluence as attachment in the page.
 *
 * This module gets Cheerio to parse the page body and search for
 * `div.ap-container[data-macro-name='drawio']` which is used to wrap the
 * drawio macro meta-data for diagrams created in the same page and search for
 * `div.ap-container[data-macro-name='inc-drawio']` which is used for
 * embedded diagrams from other pages
 *
 * Additionally, when the Confluence API v2 view format is used, drawio macros
 * are rendered as plain `<div>draw.io Board</div>` placeholders. In that case,
 * the storage body (XML) is parsed to extract diagram metadata (diagramName, pageId)
 * and the placeholder is replaced with the proper image tag.
 *
 * @param  {ConfigService} config
 * @returns void
 */
/* eslint-disable no-useless-escape, prefer-regex-literals */
export default (config: ConfigService): Step => (context: ContextService): void => {
  context.setPerfMark('fixDrawio');
  const $ = context.getCheerioBody();
  const webBasePath = config.get('web.absoluteBasePath');

  // Div class with data-macro-name='drawio' is used for Drawio diagrams created in the same page
  $(
    ".ap-container[data-macro-name='drawio'], .ap-container[data-macro-name='drawio-sketch']",
  ).each((_: number, elementDrawio: cheerio.Element) => {
    const thisBlock = $(elementDrawio).html();
    if (!thisBlock) {
      return;
    }
    const contentIdRegex = new RegExp(
      // Will find <content.id> in => "productCtx": { ... "content.id": "<content.id>" ... }
      /"productCtx".*"content.id\\":\\"(\d*)\\"/g,
    ).exec(thisBlock);
    const diagramNameRegex = new RegExp(
      // Will find <diagramName> in => "productCtx": { ... ": = | RAW | = :": ... |<diagramName>| ..." ... }
      '"productCtx".*diagramName=([^|]*).*,',
    ).exec(thisBlock);

    const [, contentId] = contentIdRegex ?? [];
    const [, diagramName] = diagramNameRegex ?? [];

    if (contentId && diagramName) {
      $(elementDrawio).prepend(
        `<figure><img class="drawio-zoomable"
                  src="${webBasePath}/wiki/download/attachments/${contentId}/${diagramName}.png"
                  alt="${diagramName}" /></figure>`,
      );
    }
  });

  // Div class with data-macro-name='inc-drawio' is used for Drawio diagrams included from other pages
  $(".ap-container[data-macro-name='inc-drawio']").each(
    (_index: number, elementDrawio: cheerio.Element) => {
      const thisBlock = $(elementDrawio).html();
      if (!thisBlock) {
        return;
      }
      // In this case finding a block with the pattern diagramDisplayName=<name-file>
      // is not enought and to  determine the name of the file we need also a hash linked to the file name
      const diagramNameRegex = new RegExp(
        // Will find <diagramName> in => "productCtx": { ... ": = | RAW | = :": ... |<diagramName>| ..." ... }
        '"productCtx".*diagramName=([^|]*).*,',
      ).exec(thisBlock);
      const aspectHashRegex = new RegExp(
        '"productCtx".*aspectHash=([^|]*).*,',
      ).exec(thisBlock);

      const [, diagramName] = diagramNameRegex ?? [];
      const [, aspectHash] = aspectHashRegex ?? [];

      if (diagramName) {
        const fileName = aspectHash
          ? `${diagramName}-${aspectHash}`
          : diagramName;
        $(elementDrawio).prepend(`
        <figure>
          <img
            class="drawio-zoomable"
            src="${webBasePath}/wiki/download/attachments/${context.getPageId()}/${fileName}.png"
            alt="${diagramName}"
          />
        </figure>`);
      }
    },
  );

  // Confluence API v2 view format renders drawio macros as plain <div>draw.io Board</div>.
  // When the old ap-container selectors didn't match, fall back to parsing the storage body
  // to extract diagram metadata and replace the placeholder divs with proper image tags.
  const drawioPlaceholders = $('div').filter(
    (_i, el) => $(el).text().trim() === 'draw.io Board',
  );
  if (drawioPlaceholders.length > 0) {
    const storageBody = context.getBodyStorage();
    if (storageBody) {
      const $xml = cheerio.load(storageBody, { xmlMode: true });
      const macros = $xml(
        String.raw`ac\:structured-macro[ac\:name="drawio"],`
        + String.raw`ac\:structured-macro[ac\:name="drawio-sketch"],`
        + String.raw`ac\:structured-macro[ac\:name="inc-drawio"]`,
      );

      drawioPlaceholders.each((idx: number, el: cheerio.Element) => {
        const macro = macros.eq(idx);
        if (!macro.length) return;

        const diagramName = macro
          .find(String.raw`ac\:parameter[ac\:name="diagramName"]`)
          .text();
        const pageId = macro
          .find(String.raw`ac\:parameter[ac\:name="pageId"]`)
          .text() || context.getPageId();

        if (diagramName) {
          $(el).replaceWith(
            `<figure><img class="drawio-zoomable"
              src="${webBasePath}/wiki/download/attachments/${pageId}/${diagramName}.png"
              alt="${diagramName}" /></figure>`,
          );
        }
      });
    }
  }

  context.getPerfMeasure('fixDrawio');
};
