import { ConfigService } from '@nestjs/config';
import * as cheerio from 'cheerio';
import { ContextService } from '../../context/context.service';
import { Step } from '../proxy-page.step';

/**
 * ### Proxy page step to replace drawio macro by the image generated by Confluence as attachment in the page.
 *
 * This module gets Cheerio to parse the page body and search for
 * `div.ap-container[data-macro-name='drawio']` which is used to wrap the
 * drawio macro meta-data for diagrams created in the same page and search for
 * `div.ap-container[data-macro-name='inc-drawio']` which is used for
 * embedded diagrams from other pages
 *
 * Additionally, when the Confluence API v2 view format is used, drawio macros
 * are rendered as plain `<div>draw.io Board</div>` placeholders. In that case,
 * the storage body (XML) is parsed to extract diagram metadata (diagramName, pageId)
 * and the placeholder is replaced with the proper image tag.
 *
 * @param  {ConfigService} config
 * @returns void
 */

type StorageDrawioMacro = {
  diagramName: string;
  pageId: string;
};

/**
 * Walk the storage XML and collect every drawio macro in document order, no
 * matter which storage shape Atlassian produced for it:
 *
 * - Legacy `<ac:structured-macro ac:name="drawio">`
 *   (also `drawio-sketch` and `inc-drawio`).
 * - New Forge ecosystem extension nodes
 *   `<ac:adf-node type="extension">` whose `extension-key` ends with
 *   `/static/drawio` (or `/static/drawio-sketch`). In that case Atlassian also
 *   emits a duplicate copy inside `<ac:adf-fallback>` which we MUST skip to
 *   keep the document-order indexing aligned with the rendered placeholders.
 */
const collectStorageDrawioMacros = (
  storageBody: string,
  fallbackPageId: string,
): StorageDrawioMacro[] => {
  const $xml = cheerio.load(storageBody, { xmlMode: true });
  const candidates = $xml(
    String.raw`ac\:structured-macro[ac\:name="drawio"],`
      + String.raw`ac\:structured-macro[ac\:name="drawio-sketch"],`
      + String.raw`ac\:structured-macro[ac\:name="inc-drawio"],`
      + String.raw`ac\:adf-node[type="extension"]`,
  );

  const macros: StorageDrawioMacro[] = [];
  candidates.each((_i, el) => {
    const $el = $xml(el);

    if ($el.is(String.raw`ac\:structured-macro`)) {
      const diagramName = $el
        .find(String.raw`ac\:parameter[ac\:name="diagramName"]`)
        .first()
        .text();
      if (!diagramName) return;
      const pageId = $el
        .find(String.raw`ac\:parameter[ac\:name="pageId"]`)
        .first()
        .text() || fallbackPageId;
      macros.push({ diagramName, pageId });
      return;
    }

    // Forge ecosystem extension: only drawio extensions, and only the
    // primary node (skip the duplicate inside <ac:adf-fallback>).
    if ($el.parents(String.raw`ac\:adf-fallback`).length > 0) return;
    const extensionKey = $el
      .find(String.raw`ac\:adf-attribute[key="extension-key"]`)
      .first()
      .text();
    if (!/\/static\/drawio(?:-sketch)?$/i.test(extensionKey)) return;
    const diagramName = $el
      .find(String.raw`ac\:adf-parameter[key="diagram-name"]`)
      .first()
      .text();
    if (!diagramName) return;
    const pageId = $el
      .find(String.raw`ac\:adf-parameter[key="page-id"]`)
      .first()
      .text() || fallbackPageId;
    macros.push({ diagramName, pageId });
  });
  return macros;
};
/**
 * Two distinct failure modes are handled client-side, since neither is
 * knowable at render time on the server:
 *  - the image fails to load at all (`onerror`, e.g. a 404/permission error)
 *  - the image loads but is Confluence's blank 1x1px placeholder, emitted
 *    when its own server-side diagram-preview export failed (`onload`)
 * In both cases `.drawio-broken` is toggled on the nearest `.drawio-figure`
 * ancestor so CSS can swap the image for a link back to the live diagram.
 */
const DRAWIO_ONLOAD = "if(this.naturalWidth<2){this.closest('.drawio-figure').classList.add('drawio-broken')}";
const DRAWIO_ONERROR = "this.closest('.drawio-figure').classList.add('drawio-broken')";

const DRAWIO_BROKEN_EXPLANATION = 'Confluence failed to generate a static preview image for this diagram '
  + '(the drawio app export did not complete). This is not a konviw issue: try republishing the '
  + 'diagram on Confluence with a real change, or export it as PNG and upload it manually as the '
  + 'page attachment.';

const buildDrawioFallback = (viewUrl: string): string => `
    <div class="drawio-fallback">
      <p>
        ⚠️ Diagram preview unavailable.
        <span class="drawio-fallback-info" tabindex="0" role="img"
          aria-label="${DRAWIO_BROKEN_EXPLANATION}"
          data-tooltip="${DRAWIO_BROKEN_EXPLANATION}">ℹ️</span>
      </p>
      <a href="${viewUrl}" target="_blank" rel="noopener noreferrer">Open diagram in Confluence</a>
    </div>`;

/** Build the markup for a drawio preview: the image itself, plus a hidden fallback (see above). */
const buildDrawioFigure = (src: string, alt: string, viewUrl: string): string => `
  <figure class="drawio-figure">
    <img class="drawio-zoomable" src="${src}" alt="${alt}"
      onload="${DRAWIO_ONLOAD}"
      onerror="${DRAWIO_ONERROR}" />
    ${buildDrawioFallback(viewUrl)}
  </figure>`;

/* eslint-disable no-useless-escape, prefer-regex-literals */
export default (config: ConfigService): Step => (context: ContextService): void => {
  context.setPerfMark('fixDrawio');
  const $ = context.getCheerioBody();
  const webBasePath = config.get('web.absoluteBasePath');
  const confluenceBaseURL = config.get('confluence.baseURL');
  const buildViewUrl = (pageId: string): string => `${confluenceBaseURL}/wiki/pages/viewpage.action?pageId=${pageId}`;

  // Div class with data-macro-name='drawio' is used for Drawio diagrams created in the same page
  $(
    ".ap-container[data-macro-name='drawio'], .ap-container[data-macro-name='drawio-sketch']",
  ).each((_: number, elementDrawio: cheerio.Element) => {
    const thisBlock = $(elementDrawio).html();
    if (!thisBlock) {
      return;
    }
    const contentIdRegex = new RegExp(
      // Will find <content.id> in => "productCtx": { ... "content.id": "<content.id>" ... }
      /"productCtx".*"content.id\\":\\"(\d*)\\"/g,
    ).exec(thisBlock);
    const diagramNameRegex = new RegExp(
      // Will find <diagramName> in => "productCtx": { ... ": = | RAW | = :": ... |<diagramName>| ..." ... }
      '"productCtx".*diagramName=([^|]*).*,',
    ).exec(thisBlock);

    const [, contentId] = contentIdRegex ?? [];
    const [, diagramName] = diagramNameRegex ?? [];

    if (contentId && diagramName) {
      $(elementDrawio).prepend(
        buildDrawioFigure(
          `${webBasePath}/wiki/download/attachments/${contentId}/${diagramName}.png`,
          diagramName,
          buildViewUrl(contentId),
        ),
      );
    }
  });

  // Div class with data-macro-name='inc-drawio' is used for Drawio diagrams included from other pages
  $(".ap-container[data-macro-name='inc-drawio']").each(
    (_index: number, elementDrawio: cheerio.Element) => {
      const thisBlock = $(elementDrawio).html();
      if (!thisBlock) {
        return;
      }
      // In this case finding a block with the pattern diagramDisplayName=<name-file>
      // is not enought and to  determine the name of the file we need also a hash linked to the file name
      const diagramNameRegex = new RegExp(
        // Will find <diagramName> in => "productCtx": { ... ": = | RAW | = :": ... |<diagramName>| ..." ... }
        '"productCtx".*diagramName=([^|]*).*,',
      ).exec(thisBlock);
      const aspectHashRegex = new RegExp(
        '"productCtx".*aspectHash=([^|]*).*,',
      ).exec(thisBlock);

      const [, diagramName] = diagramNameRegex ?? [];
      const [, aspectHash] = aspectHashRegex ?? [];

      if (diagramName) {
        const fileName = aspectHash
          ? `${diagramName}-${aspectHash}`
          : diagramName;
        $(elementDrawio).prepend(
          buildDrawioFigure(
            `${webBasePath}/wiki/download/attachments/${context.getPageId()}/${fileName}.png`,
            diagramName,
            buildViewUrl(context.getPageId()),
          ),
        );
      }
    },
  );

  // Confluence API v2 view format renders drawio macros as plain <div>draw.io Board</div>
  // (when the macro pre-render succeeded) or, since 2026-05-19, as a generic warning macro
  // body containing "Failed to load the diagram preview image. / Authentication Required /
  // Page ID: <id>" when Atlassian's server-side preview generation fails. In both cases the
  // ap-container selectors above don't match, so we fall back to parsing the storage body
  // and reconstruct the proper image tag from the drawio macro parameters. The warning-macro
  // and "draw.io Board" cases are mutually exclusive in practice (Atlassian emits one shape
  // for the whole page), so a single index-aligned correlation against the storage drawio
  // macros covers both.
  const drawioBoardPlaceholders = $('div').filter(
    (_i, el) => $(el).text().trim() === 'draw.io Board',
  );
  // We do NOT constrain on data-macro-name here: depending on the original
  // macro structure, Atlassian renders the same failure with data-macro-name
  // set to "warning", "excerpt", or other values. The drawio-specific body
  // text "Failed to load the diagram preview image" is what makes this
  // selection safe.
  const drawioWarningPlaceholders = $(
    '.confluence-information-macro-warning',
  ).filter((_i, el) =>
    $(el).text().includes('Failed to load the diagram preview image'));
  const drawioPlaceholders = drawioBoardPlaceholders.add(
    drawioWarningPlaceholders,
  );
  const storageBody = context.getBodyStorage();
  const storageMacros = storageBody
    ? collectStorageDrawioMacros(storageBody, context.getPageId())
    : [];

  if (drawioPlaceholders.length > 0 && storageMacros.length > 0) {
    drawioPlaceholders.each((idx: number, el: cheerio.Element) => {
      const macro = storageMacros[idx];
      if (!macro) return;
      $(el).replaceWith(
        buildDrawioFigure(
          `${webBasePath}/wiki/download/attachments/${macro.pageId}/${macro.diagramName}.png`,
          macro.diagramName,
          buildViewUrl(macro.pageId),
        ),
      );
    });
  }

  // Confluence sometimes resolves the extension directly into a plain
  // embedded `<img>` in the view HTML instead of a placeholder (no
  // "draw.io Board" div, no warning macro) - in that case none of the
  // selectors above match anything. Detect those by matching each image's
  // attachment URL against the drawio macros collected from the storage
  // body, and decorate them in place with the same broken-preview fallback.
  if (storageMacros.length > 0) {
    $('img').each((_i, imgEl) => {
      const $img = $(imgEl);
      if ($img.hasClass('drawio-zoomable')) return; // already handled above
      const src = $img.attr('data-image-src') || $img.attr('src') || '';
      const match = src.match(/\/download\/attachments\/(\d+)\/([^/?]+)/);
      if (!match) return;
      const [, imgPageId, encodedFilename] = match;
      let filename: string;
      try {
        filename = decodeURIComponent(encodedFilename);
      } catch {
        filename = encodedFilename;
      }
      const macro = storageMacros.find(
        (m) => m.pageId === imgPageId && `${m.diagramName}.png` === filename,
      );
      if (!macro) return;

      $img.wrap('<span class="drawio-figure"></span>');
      $img
        .addClass('drawio-zoomable')
        .attr('onload', DRAWIO_ONLOAD)
        .attr('onerror', DRAWIO_ONERROR)
        .after(buildDrawioFallback(buildViewUrl(macro.pageId)));
    });
  }

  context.getPerfMeasure('fixDrawio');
};
