name: Cypress Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    name: Cypress Run
    if: "!contains(github.event.head_commit.message, 'chore(release):')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x]
    env:
      CYPRESS_BASE_URL: https://konviw.vercel.app/cpv
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v2
        with:
          browser: chrome

      - name: 'Upload videos as Artifact'
          uses: actions/upload-artifact@v2
          with:
            name: cypress-videos
            path: tests/e2e/cypress/videos/
            retention-days: 5

      - name: 'Upload screenshots as Artifact'
          uses: actions/upload-artifact@v2
          with:
            name: cypress-screenshots
            path: tests/e2e/cypress/screenshots/
            retention-days: 5
